import "./globals.css";

import { Header } from "./components/Header";
import { Footer } from "./components/Footer";

export const metadata = {
  title: "Rick & Morty - catalogo personaggi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <>{children}</>
        <Footer />
      </body>
    </html>
  );
}
