import "./globals.css";

import { Header } from "./components/Header";
import { Footer } from "./components/Footer";

/**
 * Set the global metadata for the application
 */
export const metadata = {
  title: "Rick & Morty - catalogo personaggi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {/**
         * {children} is the placeholder for the content of each page
         */}
        <>{children}</>
        <Footer />
      </body>
    </html>
  );
}
